%% Import Script for PoleFigure Data
%
% This script was automatically created by the import wizard. You should
% run the whoole script or parts of it in order to import your data. There
% is no problem in making any changes to this script.

%% Specify Crystal and Specimen Symmetries

% crystal symmetry
CS = crystalSymmetry('6/mmm', [3 3 4.7], 'X||a*', 'Y||b', 'Z||c*', 'mineral', 'Ti');

% specimen symmetry
SS = specimenSymmetry('1');

% plotting convention
setMTEXpref('xAxisDirection','north');
setMTEXpref('zAxisDirection','intoPlane');

%% Specify File Names

% path to files
pname = '/Users/mbcx9cd4/Documents/MATLAB/sxrd/CPF_texture_plotter/intensity_data';

% which files to be imported
% fname = {...
%   [pname '/103845_peak_intensity_0002.txt'],...
%   [pname '/103845_peak_intensity_0004.txt'],...
%   [pname '/103845_peak_intensity_10-10.txt'],...
%   [pname '/103845_peak_intensity_10-11.txt'],...
%   [pname '/103845_peak_intensity_10-12.txt'],...
%   [pname '/103845_peak_intensity_10-13.txt'],...
%   [pname '/103845_peak_intensity_10-14.txt'],...
%   [pname '/103845_peak_intensity_10-15.txt'],...
%   [pname '/103845_peak_intensity_11-20.txt'],...
%   [pname '/103845_peak_intensity_11-22.txt'],...
%   [pname '/103845_peak_intensity_11-24.txt'],...
%   [pname '/103845_peak_intensity_20-20.txt'],...
%   [pname '/103845_peak_intensity_20-21.txt'],...
%   [pname '/103845_peak_intensity_20-22.txt'],...
%   [pname '/103845_peak_intensity_20-23.txt'],...
%   [pname '/103845_peak_intensity_20-24.txt'],...
%   [pname '/103845_peak_intensity_21-30.txt'],...
%   [pname '/103845_peak_intensity_21-31.txt'],...
%   [pname '/103845_peak_intensity_21-32.txt'],...
%   [pname '/103845_peak_intensity_30-30.txt'],...
%   [pname '/103845_peak_intensity_30-31.txt'],...
%   };

fname = {...
  [pname '/combined_peak_intensity_0002.txt'],...
  [pname '/combined_peak_intensity_0004.txt'],...
  [pname '/combined_peak_intensity_10-10.txt'],...
  [pname '/combined_peak_intensity_10-11.txt'],...
  [pname '/combined_peak_intensity_10-12.txt'],...
  [pname '/combined_peak_intensity_10-13.txt'],...
  [pname '/combined_peak_intensity_10-14.txt'],...
  [pname '/combined_peak_intensity_10-15.txt'],...
  [pname '/combined_peak_intensity_11-20.txt'],...
  [pname '/combined_peak_intensity_11-22.txt'],...
  [pname '/combined_peak_intensity_11-24.txt'],...
  [pname '/combined_peak_intensity_20-20.txt'],...
  [pname '/combined_peak_intensity_20-21.txt'],...
  [pname '/combined_peak_intensity_20-22.txt'],...
  [pname '/combined_peak_intensity_20-23.txt'],...
  [pname '/combined_peak_intensity_20-24.txt'],...
  [pname '/combined_peak_intensity_21-30.txt'],...
  [pname '/combined_peak_intensity_21-31.txt'],...
  [pname '/combined_peak_intensity_21-32.txt'],...
  [pname '/combined_peak_intensity_30-30.txt'],...
  [pname '/combined_peak_intensity_30-31.txt'],...
  };

%% Specify Miller Indice

h = { ...
  Miller(0,0,0,2,CS),...
  Miller(0,0,0,4,CS),...
  Miller(1, 0,-1, 0,CS),...
  Miller(1, 0,-1, 1,CS),...
  Miller(1, 0,-1, 2,CS),...
  Miller(1, 0,-1, 3,CS),...
  Miller(1, 0,-1, 4,CS),...
  Miller(1, 0,-1, 5,CS),...
  Miller(1, 1,-2, 0,CS),...
  Miller(1, 1,-2, 2,CS),...
  Miller(1, 1,-2, 4,CS),...
  Miller(2, 0,-2, 0,CS),...
  Miller(2, 0,-2, 1,CS),...
  Miller(2, 0,-2, 2,CS),...
  Miller(2, 0,-2, 3,CS),...
  Miller(2, 0,-2, 4,CS),...
  Miller(2, 1,-3, 0,CS),...
  Miller(2, 1,-3, 1,CS),...
  Miller(2, 1,-3, 2,CS),...
  Miller(3, 0,-3, 0,CS),...
  Miller(3, 0,-3, 1,CS),...
  };

%% Import the Data

% create a Pole Figure variable containing the data
pf = PoleFigure.load(fname,h,CS,SS,'interface','generic',...
  'ColumnNames', { 'Polar Angle' 'Azimuth Angle' 'Intensity'});

%% Plot the pole figures

plot(pf);
%annotate([xvector,yvector],'label',{'RD','TD'},'backgroundcolor','w')
colorbar;

%% Calculate the odf

odf = calcODF(pf, 'RESOLUTION', 5*degree);% plot some pole figure
figure;
plot(odf, 'PHI2', [0 15 30]*degree);

%% Calculate a Value for the Texture Index without specimen symmetry

TEXTURE_INDEX = textureindex(odf)

%% Plot the pole figures without contouring

d=figure;

y=[Miller(0,0,0,2,odf.CS), Miller(1,0,-1,0,odf.CS), Miller(1,1,-2,0,odf.CS)]; % include hkil figures here
plotPDF(odf,y,'antipodal','minmax') % plot without contouring
text(vector3d.X,'RD','VerticalAlignment','bottom') % moving the vector3d axis labels outside of the hemisphere boundary
text(vector3d.Y,'TD','horizontalAlignment','left')
f=gcm; % then moving up the hkil labels to make room for the rolling direction labels
f.children(1).Title.Position=[1,1.25,1] % use [-1,1.25,1] to make similar to Channel 5 and turn off minmax if you want to
f.children(2).Title.Position=[1,1.25,1]
f.children(3).Title.Position=[1,1.25,1]
CLim(gcm,[0 3]);
mtexColorbar ('location','southOutSide','title','mrd'); % move colorbar to horizontal to avoid overlap

set(gcf, 'PaperPositionMode', 'auto')