deformation_input:
# include inputs for analysing deformation behaviour here...

    thermomechanical_equipment: Dilatometer
# input the equipment, either ETMT or Dilatometer.

    thermomechanical_file_path: ../../../SXRD_raw_data/desy_2020/dilatometer_data/Ti64_Rolled_TD_Compress_950C_0.01s-1_Single-Hit_Cool_4Cs-1_ASt_new_DEF1.asc
# input path for the thermomechanical data.

    start_deformation_initial: 2000
# start number defining image numbers covering diffraction patterns during deformation.

    end_deformation_initial: 2800
# end number defining image numbers covering diffraction patterns during deformation.

    start_deformation: 2126
# start number defining image number at exact start of deformation.

    end_deformation: 2617
# end number defining image number at exact end of deformation.

    acquisition_frequency_sxrd: 10
# acquistion frequency of the synchrotron x-ray diffraction pattern images in Hz during deformation. Note, use spacing between images, rather than actual collection time.

    minimum_stress: 1
# define a minimum stress in MPa for detecting the start of deformation, default is 1 MPa.

    deform_sequence: 4
# define a sequence length for detecting the start of deformation, default is 4.

    beam_energy: 100
# beam energy in keV.

    azimuth_load_direction: 0
# give the azimuthal angle in degrees for the loading direction, note 0 degrees is horizontal, 90 degrees is vertical.

    filter_equipment: 1
# define a median filter for smoothing any noise in the equipment data, no filtering is 1.

    filter_sxrd: 1
# define a median filter for smoothing any noise in the sxrd data, no filtering is 1.

    output_file_path: ../../../SXRD_results/desy_2020/experiment{experiment_number:02d}b-deformation/fourier-peak-analysis-deformation
# output path for saving deformation analysis, excluding the experiment number.

    analogue_data_file_path: 
# input path for analogue output, used to correlate diffraction pattern images with deformation, not always possible.

    load_conversion:
# conversion of analogue signal to load (N/V).

    temperature_conversion:
# conversion of analogue signal to load (C/V).

    position_conversion: 
# conversion of analogue signal to load (mm/V). 

    number_of_points_stress: 400
# number of points to plot against true stress, typically capturing elastic to plastic transition - value of 0 will apply all points

    number_of_points_strain: 0
# number of points to plot against true strain - value of 0 will apply all points

    true_stress_limit: 220
# plot limit for true stress axis

    true_strain_limit: 0.5
# plot limit for true strain axis

    microstrain_limit: -4400
# plot limit for microstrain axis

    FWHM_limit: 0
# plot limit for full width half maximum (FWHM) axis

    intensity_limit: 0
# plot limit for intensity axis

    relative_intensity_limit: 0
# plot limit for relative intensity axis

    intensity_x_FWHM_limit: 0
# plot limit for intensity*FWHM axis

    relative_intensity_x_FWHM_limit: 0
# plot limit for relative intensity*FWHM axis