#image_numbers:
    #start:
    #end:
    #step:
# start, end and step defining the image numbers of diffraction patterns to analyse

experiment_numbers:
    experiment_start: 103840
    experiment_end: 103845
    experiment_step: 1
# start, end and step defining the experiment numbers for the sample intensity data to combine     

file_paths:
    input_text_path: ../../../SXRD_analysis/diamond_2021/{experiment_number:05d}/texture-cpf/{experiment_number:05d}-{intensity_type}-intensities/{experiment_number:05d}_peak_intensity_{label}.txt
# input path of the texture text file, excluding the experiment number, intensity type and lattice plane peak label.

    output_text_path: ../../../SXRD_analysis/diamond_2021/combined-intensities-MTEX/{experiment_start}-to-{experiment_end}-combined-{intensity_type}-intensities/combined_peak_intensity_{label}.txt
# output path for the texture text file, excluding the experiment number, intensity type and lattice plane peak label.    
    
user_inputs:
    intensity_type: raw
# intensity type of the data to combine, options inlude 'raw' or 'powder-corrected'.