deformation_input:
# include inputs for analysing deformation behaviour here...

    thermomechanical_equipment: ETMT
# input the equipment, either ETMT or Dilatometer.

    thermomechanical_file_path: ../../../SXRD_analysis/diamond_2022/026_Ti64_TIFUN-R1_RD_Deform_880C_0.1mms-1/ETMT-output/ETMT_output_026.txt
# input path for the thermomechanical data.

    start_deformation_initial: 800
# start number defining image numbers covering diffraction patterns during deformation.

    end_deformation_initial: 2800
# end number defining image numbers covering diffraction patterns during deformation.

    start_deformation: 943
# start number defining image number at exact start of deformation.

    end_deformation: 2443
# end number defining image number at exact end of deformation.

    acquisition_frequency_sxrd: 100
# acquistion frequency of the synchrotron x-ray diffraction pattern images in Hz during deformation. Note, use spacing between images, rather than actual collection time.

    minimum_stress: 1.0
# define a minimum stress in MPa for detecting the start of deformation, default is 1 MPa.

    deform_sequence: 1
# define a sequence length for detecting the start of deformation, default is 4.

    beam_energy: 89.564
# beam energy in keV.

    azimuth_load_direction: 90
# give the azimuthal angle in degrees for the loading direction, note 0 degrees is horizontal, 90 degrees is vertical.

    filter_equipment: 21
# define a median filter for smoothing any noise in the equipment data, no filtering is 1.

    filter_sxrd: 21
# define a median filter for smoothing any noise in the sxrd data, no filtering is 1.

    output_file_path: ../../../SXRD_results/diamond_2022/experiment_{experiment_number:03d}/fourier-peak-analysis-deformation
# output path for saving deformation analysis, excluding the experiment number.

    analogue_data_file_path: 
# input path for analogue output, used to correlate diffraction pattern images with deformation, not always possible.

    load_conversion:
# conversion of analogue signal to load (N/V).

    temperature_conversion:
# conversion of analogue signal to load (C/V).

    position_conversion: 
# conversion of analogue signal to load (mm/V). 

    number_of_points_stress: 400
# number of points to plot against true stress, typically capturing elastic to plastic transition - value of 0 will apply all points

    number_of_points_strain: 0
# number of points to plot against true strain - value of 0 will apply all points

    true_stress_limit: 310
# plot limit for true stress axis

    true_strain_limit: 0.07
# plot limit for true strain axis

    microstrain_limit: 5600
# plot limit for microstrain axis

    FWHM_limit: 0
# plot limit for full width half maximum (FWHM) axis

    intensity_limit: 0
# plot limit for intensity axis

    relative_intensity_limit: 0
# plot limit for relative intensity axis

    intensity_x_FWHM_limit: 0
# plot limit for intensity*FWHM axis

    relative_intensity_x_FWHM_limit: 0
# plot limit for relative intensity*FWHM axis